version: "3.2"

# Deprecated, not necessary, work with images directly from dockerhub
services:
  app:
    build:
      context: .
      args:
        UID: $U_ID
    volumes:
      - ../src:/src
    command: tail -f /dev/null
  wine:
    build:
      context: .
      dockerfile: wine.Dockerfile
    volumes:
      - ../src:/src
    command: tail -f /dev/null
    working_dir: /src