version: "3.2"

# Deprecated, not necessary, work with images directly from dockerhub
services:
  app:
    image: rtorralba/z88dk-mojon
    volumes:
      - ../src:/src
    command: tail -f /dev/null
  wine:
    image: rtorralba/wine-mojon
    volumes:
      - ../src:/src
    command: tail -f /dev/null
    working_dir: /src